### ISSUE TITLE
Increase of Color Palette Options for plotting

### ISSUE THREAD

**Issue by jpsinnecker** [grahamrow/Muview2#13]
Hi,

I would like to suggest an implementation to increase the color palette options available for plotting.

In OOMMF, you can select among a great variety of colouring options, which help the visualisation of certain specific magnetic structures. For structures that exhibit magnetic vortex, for instance, our group usually chooses the option in which pixels are coloured in white-green-black for magnetisation going from +z/0/-z. There are other palette options as well.

Thanks.
J.P.Sinnecker

**Comment by grahamrow** [comment]
Working on this now. It's kind of silly for me to hard code these options, so I'm just letting the user choose custom colors, with the sprite colors being interpolated in-between.

**Comment by jpsinnecker** [comment]
Thanks!


_\\//  -  JPS

**Comment by grahamrow** [comment]
Bet you never thought this would show up! Custom colors in master now — will add builds soon.
