### ISSUE TITLE
Incorrect link for Windows required dll

### ISSUE THREAD

**Issue by cjermain** [grahamrow/Muview2#14]
When installing on Windows, MuView 2.1.2 requires msvcr120.dll. This dll is included in [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784), instead of [Visual C++ Redistributable for Visual Studio 2012 Update 4](https://www.microsoft.com/en-us/download/details.aspx?id=30679) as the instructions suggest.

**Comment by grahamrow** [comment]
Thanks Colin, fixed the docs.
