### ISSUE TITLE
Flag to control origin of vectors in vector rendering

### ISSUE THREAD

**Issue by jpsinnecker** [grahamrow/Muview2#15]
Dear Graham,

Sometime ago I suggested to you to add some controls do allow the user to change the aspect ratio of the vector tail and head, etc. It worked perfectly.

I was wondering if you can add a kind of flag that would allow the users to choose the origin of the vector rending, i.e., tail (as it is now), middle or head. Now the each vector starts at its tail. In some of my cases, the origin of each vector in the middle will render better images.

If the feature is already in, I don't know how to use it....

Thanks!

**Comment by grahamrow** [comment]
Functionality added by 19ee9e1cbe66614fa3260fca2053902661659a18

**Comment by jpsinnecker** [comment]
Thanks again!


_\\//  -  JPS
