### ISSUE TITLE
Colormap like MuMax3?

### ISSUE THREAD

**Issue by jufiba** [grahamrow/Muview2#26]
Hi,

Muview2 (v2.1 for Linux, precompiled) has a different color map for the vector orientation than MuMax3/mumax3-convert. Would it be possible for it to use the same one?

I enclose the same structure viewed with mumax3-convert:

![mumax3](https://cloud.githubusercontent.com/assets/22659178/22016416/837e2040-dca6-11e6-820c-72ebb1117a5b.png)

and with muview2:

![muview2](https://cloud.githubusercontent.com/assets/22659178/22016418/8b1161dc-dca6-11e6-816f-bb34d59979fe.png)

**Comment by jufiba** [comment]
One comment: I think the mumax3 one is just a spectrum colormap (like, for example, the spectrum builtin lut used in ImageJ).

An alternative version of the question is if it would be possible to load an external file colormap/lut.

**Comment by grahamrow** [comment]
Hi Juan,

Interesting — I have some vague recollection that @godsic made the palettes match way back in the day. It looks to me like just the phase is off in the color map.

In more recent builds one can specify (with limitations) a user defined colormap consisting of three main colors. Could you send me a link to the OVF corresponding to those screenshots above?

Side note: I've got automatic Windows/macOS builds running now, but haven't quite sorted out linux. Pretty soon it should be trivial to get binaries out the door.

Graham

**Comment by jufiba** [comment]
Here it the link to the ovf file:
https://www.dropbox.com/s/8out35dbe2q8a2j/i1_relax.ovf?dl=0

Juan

**Comment by grahamrow** [comment]
Thanks, looking into this. Could you do me another favor and let me know if the automatic builds at https://github.com/grahamrow/Muview2/releases/tag/2.1.3.2 work for you? I don't have Linux running on metal anywhere right now, so graphics are hard to test.

**Comment by jufiba** [comment]
Yes, it works nicely. Help indicates version is 2.1.2 (running in a laptop
with Ubuntu 16.04LTS -64bits- with an intel HD4000 card, and openGL 3.3).
Now it has the same pallette as mumax3. Thanks a lot!.

Juan

El dom., 22 ene. 2017 a las 5:35, Graham Rowlands (<notifications@github.com>)
escribió:

Thanks, looking into this. Could you do me another favor and let me know if
the automatic builds at
https://github.com/grahamrow/Muview2/releases/tag/2.1.3.2 work for you? I
don't have Linux running on metal anywhere right now, so graphics are hard
to test.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grahamrow/Muview2/issues/26#issuecomment-274307799>,
or mute
the thread
