### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [grahamrow/Muview2#29]
Please provide the AppImage for download on GitHub Releases, thanks.

**Comment by grahamrow** [comment]
Hey there, still trouble shooting the build in travis. Should have the AppImage up soon!

**Comment by grahamrow** [comment]
Had to switch over to a sudo enabled container — I was reminded about the FUSE issues and saw some of your [comments](https://github.com/travis-ci/travis-ci/issues/1100) to that end. At least they finally got the sudo enabled Trusty images running. @probonopd If you have Linux running on metal could you kindly test out the AppImage [build product](https://github.com/grahamrow/Muview2/releases/tag/2.1.3.3)? Otherwise I can try on a linux machine later this week (OpenGL is too flaky for VMs or RDPs in my experience). Will close once functionality is verified.

**Comment by probonopd** [comment]
The AppImage launches and shows this window but there is no graphic inside the window by default - is this normal?

![](https://user-images.githubusercontent.com/2480569/35200088-31083e38-ff08-11e7-85d9-bf83af81bbdd.png)

**Comment by probonopd** [comment]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

References:

* https://github.com/AppImage/AppImageHub/issues/2
* https://travis-ci.org/AppImage/appimage.github.io/builds/331592889#L564

**Comment by grahamrow** [comment]
Category added, build artifact now automatically [deployed](https://github.com/grahamrow/Muview2/releases/tag/untagged-07de2e0d9a9b66f0e61b). Icon appears broken on my test systems, but it seems like icon rendering is a bit inconsistent across platforms. 

@probonopd thanks for your work on linuxdeployqt, it makes like much easier.

Closing for now.
