### ISSUE TITLE
Why is it still lag in cubes display?

### ISSUE THREAD

**Issue by XuebingZhao** [grahamrow/Muview2#31]
For large instance, I'd like to use cubes display, expecting some speed up. However all display types seem like to having same speed.

If only the surfaces are rendered, it should be much faster.

BTW, can the program utilizing GPU in future?

**Comment by grahamrow** [comment]
Hi, drawing in Muview isn't very optimized for large systems. Beyond backside culling not much is done to throw out geometry. I should probably reduce the number of openGL API calls by using instanced drawing methods, but this project is unfortunately not a priority for me at the moment.

As for GPU, I'm not sure what you mean. Everything is already rendered on the GPU using OpenGL shaders, and GPU computing wouldn't help here given the slow memory-host data transfers.

**Comment by grahamrow** [comment]
Turns out you are correct — I've been able to massively improve speeds by moving almost all computations into the GLSL and using instanced drawing commands. You can build off the feature/instanced-drawing branch until I get the CI builds working with up-to-date Qt.
