### ISSUE TITLE
muview 2.2 bug?

### ISSUE THREAD

**Issue by kongotech** [grahamrow/Muview2#35]
Thank you Grahamnrow for the very nice software!
I am, however, experiencing something that may be a bug.
When running mumax simulations, a "normal" vortex will show up as a "Neel-vortex" or antivortex in muview 2.2a1 (alpha version), however, in previous versions of muview (2.1.3.3) it does correctly show up as a "normal" vortex. 
Thought you might want to know about it.
Cheers

**Comment by grahamrow** [comment]
Thanks, this is very important! Matrix transformations are now all handled on the GPU. Could you attach an example file so I can make sure this gets fixed?

**Comment by kongotech** [comment]
Hello, The file size was 17 MB and it would not let me send it. I will
attach a screen shot of how it looks for me, and I have also sent a link to
the dropbox folder
containing the .OVF file.
I hope this helps, let me know if you need anything else or if you cannot
access the file.

I would rerun a simulation for you to get a file with a smaller size but
all GPUs are currently occupied so I cannot do that right now. So I hope
dropbox works for you.

https://www.dropbox.com/sh/2a0fe6sv5wh2o18/AAD8ThWJxDtkX4DCSM6Aapr7a?dl=0

Cheers
BE

[image: image.png]



Den tis 25 juni 2019 kl 16:35 skrev Graham Rowlands <
notifications@github.com>:

**Comment by grahamrow** [comment]
Thanks for the file, dropbox worked just fine (feel free to delete now).

I just had the wrong sign convention for the rotation matrix in the GLSL code! Now looks correct as far as I can tell — not sure how I didn't notice this earlier, so thanks for pointing this out. Will push an updated release soon.

![Screen Shot 2019-06-26 at 9 01 07 AM](https://user-images.githubusercontent.com/1561741/60181850-1d89e680-97f1-11e9-8b5c-03e57ca9c43b.png)

**Comment by kongotech** [comment]
I'm glad I could help!

Cheers,
BE

Den ons 26 juni 2019 kl 15:04 skrev Graham Rowlands <
notifications@github.com>:
